"""Reporter — 汇总所有 Agent 产出，生成 Markdown 格式的最终分析报告。

不需要 LLM——纯模板拼接。所有决策已经由前面的 Agent 做完了，
这里只负责"排版"。

设计原则：能用代码确定性地做的事，不要浪费 LLM 的 token。
"""

from ...core.config import setup_logging
from ..state import AnalysisState

logger = setup_logging(__name__)


def _format_snippets(snippets: list[dict]) -> str:
    """格式化可疑代码片段列表为 Markdown。"""
    if not snippets:
        return "_未找到可疑代码。_"

    parts = []
    for i, s in enumerate(snippets, 1):
        code = s.get("code", "")
        if code:
            code_block = f"\n```python\n{code[:1000]}\n```"
        else:
            code_block = (
                f"\n_(使用 read_file 查看 `{s.get('file_path', '?')}"
                f":{s.get('line_start', 0)}`)_"
            )

        parts.append(
            f"### {i}. `{s.get('name', '?')}` "
            f"— {s.get('file_path', '?')}:{s.get('line_start', 0)}\n"
            f"**关联原因**: {s.get('reason', '未说明')}\n"
            f"{code_block}"
        )
    return "\n".join(parts)


def _format_fixes(fixes: list[dict], votes: list[dict]) -> str:
    """格式化修复方案 + 审查结果为 Markdown。"""
    if not fixes:
        return "_未生成修复方案。_"

    # 构建 index → verdict 映射
    verdict_map = {}
    for v in votes:
        verdict_map[v.get("fix_index", -1)] = v

    parts = []
    for i, f in enumerate(fixes):
        verdict = verdict_map.get(i, {})
        status = verdict.get("verdict", "pending")
        emoji = {"approved": "✅", "rejected": "❌"}.get(status, "⏳")

        parts.append(
            f"### {emoji} 修复 {i + 1}: `{f.get('name', '?')}` "
            f"— `{f.get('file_path', '?')}`\n\n"
            f"**修复理由**: {f.get('rationale', '未说明')}\n\n"
            f"**原始代码**:\n```python\n{f.get('original_code', 'N/A')}\n```\n\n"
            f"**修复后代码**:\n```python\n{f.get('fixed_code', 'N/A')}\n```\n\n"
            f"**审查意见**: {verdict.get('feedback', '无')}"
        )
    return "\n\n".join(parts)


def reporter_node(state: AnalysisState) -> dict:
    """生成最终分析报告。不需要 LLM，纯字符串拼接。"""
    logger.info("Reporter: composing final report")

    report = f"""# 🔍 GitHub Issue 分析报告

## 📋 Issue 概要
**标题**: {state.get('issue_title', '未知')}
**错误类型**: {state.get('error_type', '未知')}

{state.get('error_context', '无上下文')}

---

## 🔎 可疑代码定位
{_format_snippets(state.get('suspicious_snippets', []))}

---

## 🔧 修复建议
{_format_fixes(state.get('fix_drafts', []), state.get('review_votes', []))}

---

## 📊 分析统计
- Explorer 搜索轮次: {state.get('explore_rounds', 0)}
- 可疑代码定位数: {len(state.get('suspicious_snippets', []))}
- 修复方案数: {len(state.get('fix_drafts', []))}
- 审查通过数: {sum(1 for v in state.get('review_votes', []) if v.get('verdict') == 'approved')}

---
_Generated by GitHub Issue Code Analyzer v2 — Multi-Agent LangGraph_
"""

    msgs = state.get("messages", [])
    msgs.append("[Reporter] 最终报告已生成")

    return {
        "final_report": report,
        "messages": msgs,
    }
